modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/cech12/ExtendedMushrooms/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="colorblindness"
    version="${file.jarVersion}"
    displayName="Color Blindness"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/colorblindness"
    authors="Cech12"
    description='''
    This mod adds potion effects for each color blindness variant.
    '''
[[dependencies.extendedmushrooms]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extendedmushrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"